### ISSUE TITLE
New sidebar-mini scroll bugs (V1.2.0)

### ISSUE THREAD

**Issue by andresprodev** [creativetimofficial/ct-paper-dashboard-pro#1]
I'm really satisfied with the new mini-sidebar, it looks great and the animation is a very good option. However, 2 problems persist with the sidebar-mini scrollbar:

1. When the page loads on a pc, the scrollbar does not display the proper css style (see screenshot).
2. The sidebar-mini allows horizontal scrolling, which should not happen (see screenshot).

![1](https://cloud.githubusercontent.com/assets/26516246/24619633/44b881c0-1860-11e7-9a53-804e81f3cdbe.jpg)

Congratulations on everything else, it's a great step forward from the previous sidebar-mini. I want to see it soon included in the material-dashboard, is there an estimated date for this?

Thank you.

Andres Ramirez
.NET Senior Web Developer

**Comment by MichiHarris** [comment]
Having this same issue, 

I've tried everything to get it to work.

Hope a solution is posted soon.

**Comment by dragosct** [comment]
Hi, @MichiHarris! Thank you for using our product. In the `v1.2.1` version of the product this issue it's fixed. Regards, Dragos
