### ISSUE TITLE
Selectpicker IE scroll problem

### ISSUE THREAD

**Issue by dragosct** [creativetimofficial/ct-paper-dashboard-pro#10]
Hi! If you want to fix the problem with the scroll of the selectpicker on IE please take the following uploaded file and go in `assets/sass/paper/plugins/_bootstrap-select.scss` and replace with the new one. After you do that please compile your scss with [Koala](koala-app.com) and please be sure that your output is `assets/css/paper-dashboard.css`. Hope this will help you! 

[_bootstrap-select.scss.zip](https://github.com/creativetimofficial/paper-dashboard-pro/files/1422533/_bootstrap-select.scss.zip)

Regards,
Dragos

**Comment by BizSnype** [comment]
Thanks, unfortunately that didn't seem to remedy the issue.  Are these changes for the .form-control dropdown select or the button dropdown?
