### ISSUE TITLE
Dropdown container causes displacement

### ISSUE THREAD

**Issue by ssaki** [creativetimofficial/ct-paper-dashboard-pro#11]
Dropdown implemented as per your documentation uses a display:block element which seems wrong for two reasons:
1) it's not unlikely for this to be used along other controls
2) in case a larger container is used the auto positioning of the menu can be quite off (sceenshot)
![screenshot from 2017-12-15 14-28-43](https://user-images.githubusercontent.com/433007/34042232-5330024c-e1a4-11e7-8230-41ccd9fa38c7.png)

As the docs/examples page on the theme uses col-3 and element that is similarly sized this is not an issue, please have a look at the following snillet
```html
<div class="row">
        <div class="col-md-12 text-right">
            <div class="dropdown">
                <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">
                    Create
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#paper">Action</a></li>
                    <li><a href="#paper">Another action</a></li>
                    <li><a href="#paper">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#paper">Separated link</a></li>
                    <li class="divider"></li>
                    <li><a href="#paper">One more separated link</a></li>
                </ul>
            </div>
        </div>
</div>
```

It seems that changing the display to  inline block solves those and has no side effects so please consider it as a fix for the next release
```css
.dropdown {
    display: inline-block;
}
```

P.S. the arrow of the menu looks weird on shorter elements as well as it's always on the right side. Perhaps this could be solved by moving on left by default unless `<ul class="dropdown-menu dropdown-menu-right">` was used? Unless there is already way to solve this in which case the documentation needs to be updated

**Comment by dragosct** [comment]
Hi, @ssaki! Thank you for using our product. Yes, you have right this is a bug and we want to thank you for your solution. We will analyze if this will break something and we will include this in the next update.

Regards,
Dragos
