### ISSUE TITLE
Modals Issue

### ISSUE THREAD

**Issue by dragosct** [creativetimofficial/ct-paper-dashboard-pro#12]
Hi! To fix the issue with the modals please take the uploaded scss partial and go to `assets/sass/paper/_sidebar-and-main-panel.scss` and replace with the new one. After that you must compile your scss with [Koala](http://koala-app.com/) and be sure that your output path is `assets/css/paper-dashboard.css`.

[_sidebar-and-main-panel.scss.zip](https://github.com/creativetimofficial/paper-dashboard-pro/files/1651678/_sidebar-and-main-panel.scss.zip)

Regard,
Dragos

**Comment by opatua** [comment]
Hi,

@dragosct10 I think you should included `_variable.scss` on your zip file. Because I realized there some of variable not declare in `_variable.scss` and when I try to compiled it's failed.
Thanks.

Regards,
Kevin

**Comment by dragosct** [comment]
I will upload also the `_variables.scss` partial. 

[_variables.scss.zip](https://github.com/creativetimofficial/paper-dashboard-pro/files/1651947/_variables.scss.zip)

Regards,
Dragos
