### ISSUE TITLE
Cannot scroll content in main-panel

### ISSUE THREAD

**Issue by maciz84** [creativetimofficial/ct-paper-dashboard-pro#13]
Hi guys,

I am using the Paper Dashboard Pro theme with vuejs and it is great, However I cannot scroll any content in my content area?

<div class="main-panel">

Could someone please tell me how I can enable scrolling please?

**Comment by maciz84** [comment]
I have tried this 

`<div class="main-panel perfect-scrollbar-on">`

 but nothing happens??

**Comment by dragosct** [comment]
Hi, @maciz84! Thank you for using our product. Please open the issue at the correct repo. 

https://github.com/creativetimofficial/vue-paper-dashboard-pro

Regards, Dragos

**Comment by maciz84** [comment]
@dragosct10 I have created the issue in the other repo

**Comment by dragosct** [comment]
Thank you, @maciz84!
