### ISSUE TITLE
Can't resolve '../fonts/nucleo-outline.svg'

### ISSUE THREAD

**Issue by twf-nikhila** [creativetimofficial/ct-paper-dashboard-pro#14]
Got this issue while compiling.

Line number 4378 needs to remove or commented to get it working.

**Comment by twf-nikhila** [comment]
Also, nucleoapp icons are not working. What should we do to fix that?

**Comment by divick** [comment]
+1

**Comment by jc0x** [comment]
please provide information on how to get nucleoapp working.
