### ISSUE TITLE
Sidenav color not changing

### ISSUE THREAD

**Issue by xmadscientist** [creativetimofficial/ct-paper-dashboard-pro#17]
When I change the data-color attribute in the sidebar div (http://prntscr.com/kq9chj) it doesn't change and shows brown. (http://prntscr.com/kq9cu2)

Any ideas?

**Comment by xmadscientist** [comment]
Also where can I find a list of icons that I can use? There is only 1 in the documentation.

**Comment by conorsomahony** [comment]
I have the same issue - data-color="white" and data-color="brown" work, but no other colors

**Comment by xmadscientist** [comment]
Anyone??

**Comment by groovemen** [comment]
Hello guys,

Thank you for using our products, this is not an issue, this is how we styled this product, as you can see in the image below, we have only 2 colors options for the background of the sidebar and 5 colors for the sidebar's items. 

<img width="378" alt="screen shot 2018-09-11 at 11 36 36" src="https://user-images.githubusercontent.com/21063398/45348301-faba7880-b5b6-11e8-9356-ba9e16ec5cee.png">


And we have an Icon page in Components, you can find it on the following link: https://demos.creative-tim.com/paper-dashboard-2-pro/examples/components/icons.html 

All the best,
Stefan

**Comment by conorsomahony** [comment]
Hi Stefan,
Thanks for the reply, I know why I thought there were more colours available, there is a comment in the html template - see below

![image](https://user-images.githubusercontent.com/25728316/45351609-7ebc3280-b5ae-11e8-9ef5-9dfb7d0c1a11.png)

**Comment by xmadscientist** [comment]
Hi Stefan,

Is it possible to add more background colors to the template for side nav bar? This is something we need.

**Comment by groovemen** [comment]
I will talk with the team and probably we'll add new colors in the next update. Best, Stefan

**Comment by xmadscientist** [comment]
Ok how will we be notified about updates @groovemen ?

**Comment by xmadscientist** [comment]
@groovemen Hello please tell me how I can change the background color of the sidenav immediately. I cannot find out how to do it anywhere in the .css file. Please help me with this issue, as it is **extremely urgent.**

**Comment by xmadscientist** [comment]
@groovemen ????

**Comment by karpinskyATL** [comment]
@xmadscientist 

In the paper-dashboard.css, search for .sidebar[data-color="brown"] and add the background colors you need  i.e.

.sidebar[data-color="blue"]:after,
.off-canvas-sidebar[data-color="blue"]:after {
    background: #1E90FF;
}

**Comment by xmadscientist** [comment]
@karpinskyATL You are a beautiful human being. I love you.
