### ISSUE TITLE
Navigation doesn't open even in demo

### ISSUE THREAD

**Issue by pxlvoid** [creativetimofficial/ct-paper-dashboard-pro#19]
eg https://demos.creative-tim.com/paper-dashboard-pro/examples/dashboard/overview.html

I'm about this: 
![screenshot2](https://user-images.githubusercontent.com/6352214/45599674-90f7ff80-b9f8-11e8-9d8a-0f47b7d9e8ac.jpg)

**Comment by pxlvoid** [comment]
@groovemen

**Comment by vnevermore** [comment]
works like a charm to meh

**Comment by groovemen** [comment]
Hello @KiraSokolov, 

Thank you for using our products, please let us know what version are you using.

Best, 
Stefan
