### ISSUE TITLE
DataTables pagination not responsive

### ISSUE THREAD

**Issue by sebastiantoro** [creativetimofficial/ct-paper-dashboard-pro#32]
Paper Dashboard 2 Pro template has a mayor bug regarding reponsiveness in DataTables. Open the DataTablet.Net section in the examples page (https://demos.creative-tim.com/paper-dashboard-2-pro/examples/tables/datatables.net.html) and then go to developer mode to see the screen as 320px wide. You will see that the pagination is broken since it keeps going past the border and it does not go to the next line.

You can do the same in DataTables.net (https://datatables.net/extensions/rowreorder/examples/initialisation/responsive.html) and you will see the correct behaviour.

**Comment by vnevermore** [comment]
same here, trying to fix it now, will post an update soon

**Comment by vnevermore** [comment]
okey here's the solution guys:
you have to add  "flex-wrap: wrap;" to your pagination css rules

before:
http://prntscr.com/nah26d
after:
http://prntscr.com/nah1h6
