### ISSUE TITLE
selectpicker live search doesn't refresh dropdown

### ISSUE THREAD

**Issue by ricardomelogon** [creativetimofficial/ct-paper-dashboard-pro#34]
![Screenshot_3](https://user-images.githubusercontent.com/15680070/57488101-571d8700-726f-11e9-9d9d-0aca4ab6cc56.png)
The standard plug-in works just fine. But when using the customized version by creative tim on Paper Dashboard the styling if off and typing on the input box does not reflect on the dropdown.

**Comment by groovemen** [comment]
Hello @ricardomelogon,

Thank you for using our products, and also sorry for this late response. I found a solution for this issue until the next update; you can notice that when you start typing into the input, the following classes **.hidden** and **.active** are set for the options: 
<img width="472" alt="Screenshot 2019-06-26 at 14 23 57" src="https://user-images.githubusercontent.com/21063398/60176242-702dc780-981e-11e9-862d-39f9bba7994e.png">

so you can set something like this:

```
.dropdown-menu {
   li.hidden {
      display: none;
   }
}
```

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
