### ISSUE TITLE
Modals are not opening in Chrome/Firefox

### ISSUE THREAD

**Issue by DrillSergeant** [creativetimofficial/ct-paper-dashboard-pro#35]
We purchased Paper Dashboard 2 PRO and have it in use in the current version 2.0.1. Since a few days we experience problem with the modals.

**Steps to reproduce:**
* Go to https://demos.creative-tim.com/paper-dashboard-2-pro/examples/components/notifications.html
* Click one of the three modal buttons (bottom of the page)

**Expected behaviour:**
The modal is shown.

**Actial behaviour:**
The modal background is shown, but the modal itself is not visible. Leaving the page in a broken state as the user cannot click anything anymore:
![image](https://user-images.githubusercontent.com/883552/57842615-34d6bc80-77cd-11e9-85f2-4de1cbbafce5.png)

**Environment:**
Happens in Chrome 74.0.3729.157 on Windows
Happens in Firefox 66.0.5 on Windows

**Strange is:**
Bug does not happen in the exact same browser version on Linux (Ubuntu 18.04 Desktop):
* Chrome and Firefox in same version as above

**Comment by DrillSergeant** [comment]
I see the last issues in this repository not getting any attention. Is this repository still maintained? @timcreative

**Comment by DrillSergeant** [comment]
I am willing to buy the Premium Support if that would help.

**Comment by groovemen** [comment]
Hello Peter, 

Thank you for using our products, we are really sorry for this late response. Also, I see that your Product Support is Inactive (has expired) and this was probably the reason why this issue wasn't solved. I double checked this issue on Mac and also on Windows OS but it works fine on both of them. 
Please try to update your browser to the latest versions. 

All the best, 
Stefan

**Comment by DrillSergeant** [comment]
Hello Stefan

Thanks for the response. I understand the support for us has expired (we bought the template more than 6 months ago), that's why we are willing to extend the support (if possible) by paying something. We would also agree to pay for this specific bug to be fix as another option.
As far as I see you are still selling this template so the issue might be a problem anyway for new customers.

I don't know why the issue does not happen on your system (with windows). Did you test with the latest Chrome and Firefox on Windows?

I retested again on Windows with those versions:
* Chrome Version 75.0.3770.80 (Offizieller Build) (64-Bit)
* Firefox 67.0.1 (64-Bit)
Issue still happens on all computers in our office (tested 12 different computers with windows). Here is a recording of that:
![Peek 2019-06-05 11-38](https://user-images.githubusercontent.com/883552/58946644-a7143e80-8786-11e9-953f-d9fa45409003.gif)

**Comment by DrillSergeant** [comment]
Seems we need to solve this ourself as the support here is not really reacting for another 3 weeks. :-( Wonder how that feels if you just bought the template as a new customer.

**Comment by groovemen** [comment]
You are the one and only customer that encountered this issue and as I told you I checked this problem on many Operating Systems and also on different browsers and IT WORKS AS EXPECTED. 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/21063398/60175302-d8c77500-981b-11e9-8fc3-b069b9858d82.gif)

Please make sure that you don't have any add-ons or extensions that block the Javascript to work.

All the best, 
Stefan

**Comment by DrillSergeant** [comment]
Sorry for being an annoying customer with a problem that is still unsolved. I am really dissapointed about your support:
* not replying for weeks
* your reaction: "cannot reproduce" => close issue => "it's your problem customer, I dont care"

Cannot imagine to handle our customer like you do handle yours.

I seldom rant, but here I cannot help myself.

**Comment by DrillSergeant** [comment]
Ok, for all the other unloved customers of createivetim:

We found out that the loading order of the js-files needs to be changed in order to get rid of this bug:
The js file `assets/js/plugins/jasny-bootstrap.min.js` needs to be loaded before `assets/js/core/bootstrap.min.js`

This solved our problem in Chrome/Windows.

**Comment by avdheshsolanki** [comment]
Was facing the same issue, so many users complaint the issue on chrome/firefox, 
Reordering the javascripts solved the issue.
Thanks DrillSergeant you made my day!
Was struggling from last 1 month. Cheers :-)

**Comment by DrillSergeant** [comment]
You are welcome. Wonder what the support thinks about the "not existing" issue.

**Comment by jamin-peckham-sp** [comment]
Pro 1.3.0, had the same issue. 
> **The js file assets/js/plugins/jasny-bootstrap.min.js needs to be loaded before assets/js/core/bootstrap.min.js**

That fixed it! So very glad, thank you for posting the solution that works.
