### ISSUE TITLE
Navbar fixed

### ISSUE THREAD

**Issue by TheNormalOne** [creativetimofficial/ct-paper-dashboard-pro#36]
Goodmorning everybody, I have this problem. Is possible fix to top navbar and mainting it Always on top when scrolling content?
Thank you

**Comment by groovemen** [comment]
Hello @TheNormalOne, 

Thank you for using our products, you can easily set a `position: static` for the navbar. Also, you will need to delete the **navbar-transparent** class and set a new background color.

Best, 
Stefan
