### ISSUE TITLE
Add package with NPM

### ISSUE THREAD

**Issue by sylvainR37** [creativetimofficial/ct-paper-dashboard-pro#37]
Hello,

I bought a license for paper dashboard 2 pro, I would install it directly as a package via npm in order to keep it up to date.

Of course I have already tried `npm install paper-dashboard-2-pro` without success.

How can I proceed?

**Comment by groovemen** [comment]
Hello @sylvainR37,

Thank you for using our products, unfortunately, we have only the Free products on npm. Sorry for the inconvenience. 

Best, Stefan

**Comment by sylvainR37** [comment]
If I want to update the template, how can I proceed in this case?

**Comment by groovemen** [comment]
You will need to replace the core files of your project.

**Comment by sylvainR37** [comment]
thx
