### ISSUE TITLE
Feature request: Add support for input type file

### ISSUE THREAD

**Issue by akshaybabloo** [creativetimofficial/ct-paper-dashboard-pro#4]
It would be great to have a Paper-dashboard support for `<input type="file" class="form-control">`.

As of now it is rendering it as

![capture](https://user-images.githubusercontent.com/7360286/28449171-e35ab98e-6e31-11e7-96a7-12d81f634b2b.JPG)

Something like https://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3 would be nice.

**Comment by alexandru-paduraru** [comment]
@akshaybabloo thank you for the suggestion, we will add it in the next release. Till then we recommend you this library: http://www.jasny.net/bootstrap/javascript/#fileinput 

It should look fine with our current style. 

Best,
Alex
