### ISSUE TITLE
The documentation link for Paper Dashboard is not working

### ISSUE THREAD

**Issue by sethura** [creativetimofficial/ct-paper-dashboard-pro#43]
I purchased Paper Dashboard product but when I go to documentation link: https://demos.creative-tim.com/paper-dashboard-pro-angular/documentation/tutorial it does not work .

Please provide the correct access link to documentation for Paper Dashboard product for Angular edition.

**Comment by dragosct** [comment]
Hi, @sethura! Thank you for using our products. Please, when you have an issue open that issue on the proper repo because this repo is only for the HTML version. Now regard to your issue my colleague @chelaruc will help you. 

Regards, 
Dragos

**Comment by chelaruc** [comment]
Hi, @sethura. The documentation link is: [https://demos.creative-tim.com/paper-dashboard-pro-angular/#/documentation/tutorial](https://demos.creative-tim.com/paper-dashboard-pro-angular/#/documentation/tutorial)
