### ISSUE TITLE
svg used in scss but not included 2.1.1

### ISSUE THREAD

**Issue by ChrisToxz** [creativetimofficial/ct-paper-dashboard-pro#61]
**_nucleo_-outline.scss** line 10:
`url('../fonts/nucleo-icons.svg') format('svg')`
Ask for SVG but not included.
I had read in another repo issue that you don't use svg anymore.

Please include .svg into the download or change this line.

**Comment by groovemen** [comment]
Hello @ChrisToxz,

Thank you for your interest in working with our products, I will discuss with my colleagues and change the SCSS file for the next product update. Thank you for letting us know about this issue. 

All the best, 
Stefan
