### ISSUE TITLE
Datetimepicker calendar not showing

### ISSUE THREAD

**Issue by kchiey** [creativetimofficial/ct-paper-dashboard-pro#8]
I want to use the datetimepicker in my project. When I try the original forms/extended.html, the datetimepicker works fine. But, when I implement it into the new php file, the calendar did not come out. I didn't do many changes though. I just do a little bit modification on my content only, the rest are the same code with the forms/extended.html. 

Is it because i'm using the wizard form? I put the datetimepicker input inside the wizard form.

**Comment by alexandru-paduraru** [comment]
Thank you for using our product. It seems you have the datetimepicker inside a step of the wizard which by default is hidden, that means the browser cannot see what you have in step 2-3-4-5 if you are on step 1. So you need to call the initialisation of the datetimepicker after "you arrive" on the step which contains that datetimepicker.

Something like:
```
if (index == stepWhereIhavetheDatepicker){
   // init datetimepicker here
}
```
You should add this condition inside the `onTabShow` method: http://vinceg.github.io/twitter-bootstrap-wizard/examples/basic-formvalidation.html

More examples about how to how to work with the steps of the wizard can be found on the original documentation: http://vinceg.github.io/twitter-bootstrap-wizard/

Hope this helps.

Best,
Alex

**Comment by cdhz** [comment]
this is my problem to please help me

**Comment by cdhz** [comment]
<script>
 $(document).ready(function() { 
      $('#rootwizard').bootstrapWizard({onNext: function(tab, navigation, index) { 

      }, onTabShow: function(tab, navigation, index) {
        if(index==2) {
          $('#sqDate').datetimepicker({ format: 'MM/DD/YYYY'});
        $('#pcApprox').datetimepicker({ format: 'MM/DD/YYYY'});
        $('#pcEnd').datetimepicker({ format: 'MM/DD/YYYY'});
        }
        var $total = navigation.find('li').length;
        var $current = index+1;
        var $percent = ($current/$total) * 100;
        $('#rootwizard .progress-bar').css({width:$percent+'%'});
      }});
    window.prettyPrint && prettyPrint()
   });
        
  </script>
