### ISSUE TITLE
Cannot have a single checkbox

### ISSUE THREAD

**Issue by akshaybabloo** [creativetimofficial/ct-paper-dashboard-pro#9]
There should be more than one checkbox only then it is visible. Even the horizontal login form in - http://demos.creative-tim.com/paper-dashboard-pro/examples/forms/regular.html - shows empty.

Could you please fix it.

**Comment by dragosct** [comment]
Hi, @akshaybabloo! For fixing this please go in `examples/forms/regular.html` and search for `Stacked Form` and `Horizontal Form`. Inside of these cards you will find checkboxes with the following code:

```html
  <label class="checkbox">
       <input type="checkbox" data-toggle="checkbox" value="" checked="">
       Subscribe to newsletter
  </label>

  <label class="checkbox">
       <input type="checkbox" data-toggle="checkbox" value="" checked="">
       Remember Me
  </label>
  
```

The code must be changed with this:

```html
  <div class="checkbox">
        <input id="checkbox1" type="checkbox">
        <label for="checkbox1">Subscribe to newsletter</label>
  </div>
 
 <div class="checkbox">
        <input id="checkbox2" type="checkbox">
        <label for="checkbox2">Remember Me</label>
  </div> 
```

The `id`'s for this checkboxes can have any value that you want and must be the same value with the value of the attribute `for` from the label tag. We will fix this also in the next update. 

Regards,
Dragos

**Comment by akshaybabloo** [comment]
Hi @dragosct10. This helped, but I'll keep this ticket open until the new release. Thanks.
